### ISSUE TITLE
Add a license to improve discoverability

### ISSUE THREAD

**Issue by klaude** [kraney/stackpath#2]
Howdy, @kraney. One of our team members noticed that we can't browse the contents of this library on pkg.go.dev. For instance, the [accounts_and_users package](https://pkg.go.dev/github.com/kraney/stackpath@v0.0.0-20200905234818-2f615e4dc8b6/pkg/accounts_and_users) won't display due to pkg.go.dev's [license policy](https://pkg.go.dev/license-policy). If you adopt one of their supported licenses then others will be able to see README contents and other package information, which should lead to more adoption of the library. Just thought we'd point it out. Thanks for making this!

**Comment by kraney** [comment]
An oversight, thanks for pointing it out!
